/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article_inner: typeof import('./components/subArticle/article_inner.vue')['default']
    ArticleDisplay: typeof import('./components/discover/ArticleDisplay.vue')['default']
    Becomment: typeof import('./components/notify/becomment/becomment.vue')['default']
    Cart: typeof import('./components/cart/cart.vue')['default']
    Chlid: typeof import('./components/child/Chlid.vue')['default']
    Comment: typeof import('./components/comment/Comment.vue')['default']
    Discover: typeof import('./components/discover/Discover.vue')['default']
    Like_button: typeof import('./components/subArticle/like_button.vue')['default']
    Like_comment: typeof import('./components/comment/like_comment/like_comment.vue')['default']
    Like_star: typeof import('./components/notify/like_star/like_star.vue')['default']
    LikeList: typeof import('./components/me/meInfo/LikeList.vue')['default']
    Loged: typeof import('./components/loged/Loged.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    MainBody: typeof import('./components/mainBody/MainBody.vue')['default']
    Market: typeof import('./components/market/Market.vue')['default']
    Me: typeof import('./components/me/Me.vue')['default']
    MyHeader: typeof import('./components/MyHeader/MyHeader.vue')['default']
    NewSubscript: typeof import('./components/notify/newSubscript/newSubscript.vue')['default']
    Note: typeof import('./components/me/meInfo/Note.vue')['default']
    Notify: typeof import('./components/notify/Notify.vue')['default']
    Publish: typeof import('./components/publish/Publish.vue')['default']
    ReplyPart: typeof import('./components/comment/replyPart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Square: typeof import('./components/square/square.vue')['default']
    StarList: typeof import('./components/me/meInfo/StarList.vue')['default']
    SubArticle: typeof import('./components/subArticle/subArticle.vue')['default']
    Subscript: typeof import('./components/notify/newSubscript/subscript.vue')['default']
    UserList: typeof import('./components/discover/UserList.vue')['default']
  }
}
