/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/admin/AdminLayout.vue')['default']
    Article_inner: typeof import('./components/subArticle/article_inner.vue')['default']
    ArticleDisplay: typeof import('./components/discover/ArticleDisplay.vue')['default']
    ArticleList: typeof import('./components/discover/ArticleList.vue')['default']
    Becomment: typeof import('./components/notify/becomment/becomment.vue')['default']
    Book: typeof import('./components/me/meInfo/Book.vue')['default']
    Book_detail: typeof import('./components/market/book_detail/book_detail.vue')['default']
    Book_details: typeof import('./components/market/book_details/book_details.vue')['default']
    Book_item: typeof import('./components/market/book_item/book_item.vue')['default']
    Card: typeof import('./components/cart/card/card.vue')['default']
    Cart: typeof import('./components/cart/cart.vue')['default']
    Chlid: typeof import('./components/child/Chlid.vue')['default']
    Comment: typeof import('./components/comment/Comment.vue')['default']
    Discover: typeof import('./components/discover/Discover.vue')['default']
    DiscoverTest: typeof import('./components/discover/DiscoverTest.vue')['default']
    EditProfile: typeof import('./components/profile/EditProfile.vue')['default']
    Like_button: typeof import('./components/subArticle/like_button.vue')['default']
    Like_comment: typeof import('./components/comment/like_comment/like_comment.vue')['default']
    Like_star: typeof import('./components/notify/like_star/like_star.vue')['default']
    LikeList: typeof import('./components/me/meInfo/LikeList.vue')['default']
    Loged: typeof import('./components/loged/Loged.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    MainBody: typeof import('./components/mainBody/MainBody.vue')['default']
    Market: typeof import('./components/market/Market.vue')['default']
    Me: typeof import('./components/me/Me.vue')['default']
    MyHeader: typeof import('./components/MyHeader/MyHeader.vue')['default']
    NewSubscript: typeof import('./components/notify/newSubscript/newSubscript.vue')['default']
    Note: typeof import('./components/me/meInfo/Note.vue')['default']
    Notify: typeof import('./components/notify/Notify.vue')['default']
    PrivateChat: typeof import('./components/notify/PrivateChat.vue')['default']
    Publish: typeof import('./components/publish/Publish.vue')['default']
    Register: typeof import('./components/login/Register.vue')['default']
    ReplyPart: typeof import('./components/comment/replyPart.vue')['default']
    ReportDialog: typeof import('./components/report/ReportDialog.vue')['default']
    ReportManagement: typeof import('./components/report/ReportManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleWaterfall: typeof import('./components/discover/SimpleWaterfall.vue')['default']
    Square: typeof import('./components/square/square.vue')['default']
    StarList: typeof import('./components/me/meInfo/StarList.vue')['default']
    SubArticle: typeof import('./components/subArticle/subArticle.vue')['default']
    Subscript: typeof import('./components/notify/newSubscript/subscript.vue')['default']
    Transactions: typeof import('./components/notify/transactions.vue')['default']
    UserList: typeof import('./components/discover/UserList.vue')['default']
    VirtualWaterfall: typeof import('./components/discover/VirtualWaterfall.vue')['default']
    VirtualWaterfallTest: typeof import('./components/discover/VirtualWaterfallTest.vue')['default']
    WaterfallTest: typeof import('./components/discover/WaterfallTest.vue')['default']
  }
}
